-- MySQL Script generated by MySQL Workbench
-- 05/26/17 13:39:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema login
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `login` DEFAULT CHARACTER SET latin1 ;
USE `login` ;

-- -----------------------------------------------------
-- Table `login`.`tbl_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`tbl_members` (
  `ID` INT(15) NOT NULL AUTO_INCREMENT COMMENT '',
  `userName` VARCHAR(31) NOT NULL COMMENT '',
  `emailID` VARCHAR(31) NOT NULL COMMENT '',
  `pass` VARCHAR(31) NOT NULL COMMENT '',
  `Foto` LONGBLOB NULL DEFAULT NULL COMMENT '',
  `Nacimiento` DATE NULL DEFAULT NULL COMMENT '',
  `Puesto` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Paterno` VARCHAR(45) NULL COMMENT '',
  `Materno` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(80) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `mID` (`userName` ASC, `emailID` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `login`.`Medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Medida` (
  `idMedida` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idMedida`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Fluido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Fluido` (
  `idFluido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Medida_idMedida` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFluido`)  COMMENT '',
  INDEX `fk_Fluido_Medida1_idx` (`Medida_idMedida` ASC)  COMMENT '',
  CONSTRAINT `fk_Fluido_Medida1`
    FOREIGN KEY (`Medida_idMedida`)
    REFERENCES `login`.`Medida` (`idMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Periodo` (
  `idPeriodo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Cantidad` DOUBLE NOT NULL COMMENT '',
  `Periodo` DATE NOT NULL COMMENT '',
  `Fluido_idFluido` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idPeriodo`)  COMMENT '',
  INDEX `fk_Periodo_Fluido1_idx` (`Fluido_idFluido` ASC)  COMMENT '',
  CONSTRAINT `fk_Periodo_Fluido1`
    FOREIGN KEY (`Fluido_idFluido`)
    REFERENCES `login`.`Fluido` (`idFluido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Estado_Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Estado_Solicitud` (
  `idEstado` INT NOT NULL COMMENT '',
  `Estado` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idEstado`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Solicitudes` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Hora` TIME(4) NULL COMMENT '',
  `Solicitud` VARCHAR(150) NULL COMMENT '',
  `tbl_members_ID` INT(15) NOT NULL COMMENT '',
  `Estado_idEstado` INT NOT NULL COMMENT '',
  `Mensaje` VARCHAR(25) NULL COMMENT '',
  PRIMARY KEY (`idSolicitud`)  COMMENT '',
  INDEX `fk_Solicitudes_tbl_members1_idx` (`tbl_members_ID` ASC)  COMMENT '',
  INDEX `fk_Solicitudes_Estado1_idx` (`Estado_idEstado` ASC)  COMMENT '',
  CONSTRAINT `fk_Solicitudes_tbl_members1`
    FOREIGN KEY (`tbl_members_ID`)
    REFERENCES `login`.`tbl_members` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Solicitudes_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `login`.`Estado_Solicitud` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Boletin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Boletin` (
  `idBoletin` INT NOT NULL COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Hora` TIME(4) NULL COMMENT '',
  `Asunto` VARCHAR(25) NULL COMMENT '',
  `Mensaje` VARCHAR(250) NULL COMMENT '',
  PRIMARY KEY (`idBoletin`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`departamento` (
  `iddepartamento` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`iddepartamento`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`idequipo`)  COMMENT '',
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`departamento_has_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`departamento_has_equipo` (
  `departamento_iddepartamento` INT NOT NULL COMMENT '',
  `equipo_idequipo` INT NOT NULL COMMENT '',
  `cantidad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`departamento_iddepartamento`, `equipo_idequipo`)  COMMENT '',
  INDEX `fk_departamento_has_equipo_equipo1_idx` (`equipo_idequipo` ASC)  COMMENT '',
  INDEX `fk_departamento_has_equipo_departamento1_idx` (`departamento_iddepartamento` ASC)  COMMENT '',
  CONSTRAINT `fk_departamento_has_equipo_departamento1`
    FOREIGN KEY (`departamento_iddepartamento`)
    REFERENCES `login`.`departamento` (`iddepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamento_has_equipo_equipo1`
    FOREIGN KEY (`equipo_idequipo`)
    REFERENCES `login`.`equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Proveedor` (
  `idProveedor` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(100) NOT NULL COMMENT '',
  `Representante` VARCHAR(100) NULL COMMENT '',
  `Domicilio` VARCHAR(150) NOT NULL COMMENT '',
  `Ciudad` VARCHAR(60) NOT NULL COMMENT '',
  `Estado` VARCHAR(60) NOT NULL COMMENT '',
  `RFC` VARCHAR(45) NOT NULL COMMENT '',
  `Telefono` VARCHAR(12) NULL COMMENT '',
  `Email` VARCHAR(120) NOT NULL COMMENT '',
  `Codpostal` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idProveedor`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Baja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Baja` (
  `idBaja` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Expediente` INT NULL COMMENT '',
  `Proveedores_idProveedor` INT NULL COMMENT '',
  PRIMARY KEY (`idBaja`)  COMMENT '',
  INDEX `fk_Baja_Proveedores1_idx` (`Proveedores_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Baja_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `login`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Descripcion` (
  `Cantidad` INT NULL COMMENT '',
  `Descripción` VARCHAR(150) NULL COMMENT '',
  `PrecioUnitario` DOUBLE NULL COMMENT '',
  `Renglon` VARCHAR(45) NULL COMMENT '',
  `Plazo` VARCHAR(45) NULL COMMENT '',
  `Factura_idFactura` INT NOT NULL COMMENT '',
  INDEX `fk_Descripcion_Factura1_idx` (`Factura_idFactura` ASC)  COMMENT '',
  CONSTRAINT `fk_Descripcion_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `login`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Estado` (
  `Nuevo` VARCHAR(5) NULL COMMENT '',
  `Operando` VARCHAR(5) NULL COMMENT '',
  `FueraOperacion` VARCHAR(5) NULL COMMENT '',
  `Suspension` VARCHAR(5) NULL COMMENT '',
  `Sobrante` VARCHAR(5) NULL COMMENT '',
  `Fallas` VARCHAR(5) NULL COMMENT '',
  `Otros` VARCHAR(25) NULL COMMENT '',
  `SuspensionServicio` VARCHAR(5) NULL COMMENT '',
  `Sobrante2` VARCHAR(5) NULL COMMENT '',
  `Siniestro` VARCHAR(5) NULL COMMENT '',
  `Inutil` VARCHAR(5) NULL COMMENT '',
  `CambioProyecto` VARCHAR(5) NULL COMMENT '',
  `Inadecuando` VARCHAR(5) NULL COMMENT '',
  `Completo` VARCHAR(5) NULL COMMENT '',
  `Baja_idBaja` INT NOT NULL COMMENT '',
  INDEX `fk_Estado_Baja1_idx` (`Baja_idBaja` ASC)  COMMENT '',
  CONSTRAINT `fk_Estado_Baja1`
    FOREIGN KEY (`Baja_idBaja`)
    REFERENCES `login`.`Baja` (`idBaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`EvaluacionTecnica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`EvaluacionTecnica` (
  `Condiciones` VARCHAR(5) NULL COMMENT '',
  `OperacionPersonal` VARCHAR(5) NULL COMMENT '',
  `Especializado` VARCHAR(5) NULL COMMENT '',
  `Mantenimiento` VARCHAR(5) NULL COMMENT '',
  `Bienes` VARCHAR(5) NULL COMMENT '',
  `CondicionesAd` VARCHAR(5) NULL COMMENT '',
  `FallasFrec` VARCHAR(50) NULL COMMENT '',
  `FrecuenciaFalla` VARCHAR(25) NULL COMMENT '',
  `CostoRepara` DOUBLE NULL COMMENT '',
  `CostoReposicion` DOUBLE NULL COMMENT '',
  `MantenimientoAnual` VARCHAR(5) NULL COMMENT '',
  `Desinstalador` VARCHAR(60) NULL COMMENT '',
  `Baja_idBaja` INT NOT NULL COMMENT '',
  INDEX `fk_EvaluacionTecnica_Baja1_idx` (`Baja_idBaja` ASC)  COMMENT '',
  CONSTRAINT `fk_EvaluacionTecnica_Baja1`
    FOREIGN KEY (`Baja_idBaja`)
    REFERENCES `login`.`Baja` (`idBaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Dictamen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Dictamen` (
  `ProcedeBajaUnidad` VARCHAR(5) NULL COMMENT '',
  `EnajeDelega` VARCHAR(5) NULL COMMENT '',
  `ReubiDelega` VARCHAR(5) NULL COMMENT '',
  `NoProcedencia` VARCHAR(5) NULL COMMENT '',
  `NoProcedeBaja` VARCHAR(5) NULL COMMENT '',
  `DebeContOpera` VARCHAR(5) NULL COMMENT '',
  `DebeRepRecProp` VARCHAR(5) NULL COMMENT '',
  `DebeCapaOperado` VARCHAR(5) NULL COMMENT '',
  `DebeRepApoyoTec` VARCHAR(5) NULL COMMENT '',
  `DebeRepRecExt` VARCHAR(5) NULL COMMENT '',
  `DebeCapOpMant` VARCHAR(5) NULL COMMENT '',
  `ReubNivCent` VARCHAR(5) NULL COMMENT '',
  `ProceBajaDef` VARCHAR(5) NULL COMMENT '',
  `Baja_idBaja` INT NOT NULL COMMENT '',
  INDEX `fk_Dictamen_Baja1_idx` (`Baja_idBaja` ASC)  COMMENT '',
  CONSTRAINT `fk_Dictamen_Baja1`
    FOREIGN KEY (`Baja_idBaja`)
    REFERENCES `login`.`Baja` (`idBaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`CausaBaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`CausaBaja` (
  `EquipoSobNuevo` VARCHAR(5) NOT NULL COMMENT '',
  `Obsolencia` VARCHAR(5) NULL COMMENT '',
  `Inutilidad` VARCHAR(5) NULL COMMENT '',
  `SuspensionServicio` VARCHAR(5) NULL COMMENT '',
  `CamCapProyOrig` VARCHAR(5) NULL COMMENT '',
  `CarenServEspLoc` VARCHAR(5) NULL COMMENT '',
  `CarenServEspNac` VARCHAR(5) NULL COMMENT '',
  `Siniestrado` VARCHAR(5) NULL COMMENT '',
  `Otros` VARCHAR(25) NULL COMMENT '',
  `FallaRefMerNac` VARCHAR(5) NULL COMMENT '',
  `FaltaRefMerInt` VARCHAR(5) NULL COMMENT '',
  `FallaFrec` VARCHAR(5) NULL COMMENT '',
  `EquipoIncomp` VARCHAR(5) NULL COMMENT '',
  `ProyectoInadecuado` VARCHAR(5) NULL COMMENT '',
  `InadeSelecEquipo` VARCHAR(5) NULL COMMENT '',
  `Robado` VARCHAR(5) NULL COMMENT '',
  `Extraviado` VARCHAR(5) NULL COMMENT '',
  `Baja_idBaja` INT NOT NULL COMMENT '',
  INDEX `fk_CausaBaja_Baja1_idx` (`Baja_idBaja` ASC)  COMMENT '',
  CONSTRAINT `fk_CausaBaja_Baja1`
    FOREIGN KEY (`Baja_idBaja`)
    REFERENCES `login`.`Baja` (`idBaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Partida` (
  `idPartida` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idPartida`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Factura` (
  `idFactura` INT NOT NULL COMMENT '',
  `Fecha` DATE NULL COMMENT '',
  `Calsificacion` VARCHAR(45) NULL COMMENT '',
  `Facturacol` VARCHAR(45) NULL COMMENT '',
  `Orden` VARCHAR(45) NULL COMMENT '',
  `Proveedores_idProveedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idFactura`)  COMMENT '',
  INDEX `fk_Factura_Proveedores1_idx` (`Proveedores_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Factura_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `login`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Descripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Descripcion` (
  `Cantidad` INT NULL COMMENT '',
  `Descripción` VARCHAR(150) NULL COMMENT '',
  `PrecioUnitario` DOUBLE NULL COMMENT '',
  `Renglon` VARCHAR(45) NULL COMMENT '',
  `Plazo` VARCHAR(45) NULL COMMENT '',
  `Factura_idFactura` INT NOT NULL COMMENT '',
  INDEX `fk_Descripcion_Factura1_idx` (`Factura_idFactura` ASC)  COMMENT '',
  CONSTRAINT `fk_Descripcion_Factura1`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `login`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Contrato` (
  `idContrato` INT NOT NULL COMMENT '',
  `Descripcion` VARCHAR(100) NOT NULL COMMENT '',
  `Proveedores_idProveedor` INT NOT NULL COMMENT '',
  `Archivo` LONGBLOB NULL COMMENT '',
  PRIMARY KEY (`idContrato`)  COMMENT '',
  INDEX `fk_Contrato_Proveedores1_idx` (`Proveedores_idProveedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Contrato_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `login`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `login`.`Partida_has_Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `login`.`Partida_has_Proveedores` (
  `Partida_idPartida` INT NOT NULL COMMENT '',
  `Proveedores_idProveedor` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Partida_idPartida`, `Proveedores_idProveedor`)  COMMENT '',
  INDEX `fk_Partida_has_Proveedores_Proveedores1_idx` (`Proveedores_idProveedor` ASC)  COMMENT '',
  INDEX `fk_Partida_has_Proveedores_Partida1_idx` (`Partida_idPartida` ASC)  COMMENT '',
  CONSTRAINT `fk_Partida_has_Proveedores_Partida1`
    FOREIGN KEY (`Partida_idPartida`)
    REFERENCES `login`.`Partida` (`idPartida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_has_Proveedores_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `login`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
